default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1d9stdq394jcygkqhtweuep34ctlqj5n7zn5qezqt6y6egvkw5djs723mzn"]

[secrets]
""= { provider = "age" }
OPENROUTER_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaHV5Tzg1OExNbEY3U2VtK0QvWWFCZmFhNnFYa1ZyeG11Rkh2a093M0M0ClUwaDE1ay95azg2dGViMEltNHV3RGxyWWk5a0FnME5DdE4yZENycmtPU00KLT4gdGotZ3JlYXNlIGs9MHZNICRXZHlCIG1YMiA1Jz8jcgordjg3OVJYbm9XVlRPQ3hFNzFkZXNOaGhCbE5PWVRQSkdGNmRYMHRMaTQxNllvN2J4MkFQM2l2NkRYbWZpU0xzCjMrTUlGY3duekdEMXdDczJ1UlB3RzBZV2JMMFRMZDJYQWRpdkQ5bDRTV0tQUFRYOCtqaFF5MkdlaHhuaQotLS0gYktWK0hvU1haNTQwNVhIcFR4ZVA4RlFwRm9SeXFKUVhVRk9FNGRFT1krZwqLKyrcDoiSVAYAAHtdIKRwwJ0rZIPwLEGP89Ac3uNDmEb9jBtikcpQBG+fx1KtnCBvhwI9su4K76qcGR396ZrC/5cfapeOHiAVrUPBP8VSwqJvA9XsAlCSAuaHWeoNV6xlg9vfv5P/b80=" }
OPENCODE_ZEN_API_KEY= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWnlSeGN5SUkvWTFLYW9NdWFuQS93bFN1bHlYM3hIRzhpNXBVS250NmhBCmoramlhK2ZkbDY5dmJVdXRiRjRSdWdrMW5SWFQybGdKazQxRkVMb0x6djAKLT4gPydfdk8vLWdyZWFzZQpSMmVKeHVYR1dHQUlHcGpBVG5hWlV1U0tUY25RNnh3NXFUd2hacHNKK2EyUDRCc2Q1ZXZFCi0tLSAwVkRHYVE4UHF6dXE3aXR2NXhKWEVSa2hRWHdrbER5NTRKbFhncXR1SjVjChm5QHdsO9AnImQykFEN+HmI0UfL1s+LxHXeZJAAX6weBOc95eXDu5lM+cOE0e1b7wASz3JhCB9vsUYyJHnpSj865Nq0NIeKODEA0ECWTMhVup6EcRkPXrkOjZgKNWi13fHoNA==" }
