[bootstrap.packages]
"pacman:git"        = { os = "linux", version = "latest" }
"pacman:base-devel" = { os = "linux", version = "latest" }
# Various LISPs
"pacman:roswell" = { os = "linux", version = "latest" }
"pacman:racket"  = { os = "linux", version = "latest" }
"pacman:chicken" = { os = "linux", version = "latest" }
"pacman:guile"   = { os = "linux", version = "latest" }
"pacman:sbcl"    = { os = "linux", version = "latest" }
# Fonts 
"pacman:ttf-iosevka-nerd"         = { os = "linux", version = "latest" }
"pacman:ttf-iosevkaterm-nerd"     = { os = "linux", version = "latest" }
"pacman:ttf-iosevkatermslab-nerd" = { os = "linux", version = "latest" }
"pacman:ttf-fira-code"            = { os = "linux", version = "latest" }
"pacman:ttf-hack-nerd"            = { os = "linux", version = "latest" }
"pacman:ttf-lilex-nerd"           = { os = "linux", version = "latest" }

[deps.bun]
auto = true
[deps.pnpm]
auto = true

[tool_alias]
oh-my-pi = "github:can1357/oh-my-pi"
gbrain = "github:garrytan/gbrain"
deja = "github:Giammarco-Ferranti/deja"
zhist = "github:overflowy/zhist"

[tools]
# Core
node = "latest"
bun = "latest"
pnpm = "latest"
worktrunk = "latest"
uv = "latest"
java = "latest"
babashka = "latest"
clojure = "latest"

# AI-related
herdr = "latest"
hunk = "latest"
"llama.cpp" = { version = "latest", version_prefix = "b" }
oh-my-pi = "latest"
ollama = "latest"
opencode = "latest"
pi = "latest"
gbrain = "latest"

# Secrets management
fnox = "latest"

# Deps
"npm:prettier" = "latest"
"npm:markdownlint-cli2" = "0.23.2"
"npm:eslint" = "latest"
"npm:pi-nvim-bridge" = "latest"

[tools.deja]
version = "latest"
postinstall = "deja import"

[tools.zhist]
version = "latest"
postinstall = "zhist import ~/.histfile"
