[tools]
fnox = "latest"
"github:can1357/oh-my-pi" = "latest"
herdr = "latest"
hunk = "latest"
"llama.cpp" = { version = "latest", version_prefix = "b" }
markdownlint-cli2 = "latest"
node = "latest"
ollama = "latest"
opencode = "latest"
pi = "latest"
pnpm = "latest"
prettier = "latest"
worktrunk = "latest"
